# Generated by Django 5.2.4 on 2025-09-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_feedback_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(help_text='Введите ваше имя', max_length=155, verbose_name='Имя'),
        ),
    ]
