# Generated by Django 5.2.4 on 2025-09-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_feedback_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='content',
            field=models.TextField(help_text='Введите текст сообщения', verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(help_text='Введите вашу почту', max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='send_time',
            field=models.DateTimeField(auto_now_add=True, help_text='Время отправки сообщения', verbose_name='Время отправки'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='title',
            field=models.CharField(help_text='Введите тему сообщения', max_length=155, verbose_name='Тема'),
        ),
    ]
