# Generated by Django 5.2.4 on 2025-09-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_feedback_content_alter_feedback_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='graduate_status',
            field=models.CharField(choices=[('employed', 'Устроился'), ('searching', 'Ищет работу'), ('not_interested', 'Незаинтересован')], default='searching', help_text='Текущее состояние выпускника', max_length=20, verbose_name='Статус выпускника'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_graduate',
            field=models.BooleanField(default=False, verbose_name='Выпускник'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='institution',
            field=models.CharField(choices=[('MUIT', 'МУИТ'), ('KITE', 'КИТЭ'), ('COMTEHNO', 'КОМТЕХНО')], max_length=50, verbose_name='Учебное заведение'),
        ),
    ]
